// Generated by CoffeeScript 1.4.0
(function() {
  var ALPHABET, CSS_COLOR_NAMES, EXERCICES, FUNCTION, ahead_vars, color_tab, debug, delay, delta, id, infobox, interval, looping, renderArbor, renderPacks, tags, var_tab, _ref,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Array.prototype.unique = function() {
    var key, output, value, _i, _ref, _results;
    output = {};
    for (key = _i = 0, _ref = this.length; 0 <= _ref ? _i < _ref : _i > _ref; key = 0 <= _ref ? ++_i : --_i) {
      output[this[key]] = this[key];
    }
    _results = [];
    for (key in output) {
      value = output[key];
      _results.push(value);
    }
    return _results;
  };

  delay = function(ms, func) {
    return setTimeout(func, ms);
  };

  interval = function(ms, func) {
    return setInterval(func, ms);
  };

  _ref = [[], [], {}, true, true, false, false, false, true, 0, 550], color_tab = _ref[0], ahead_vars = _ref[1], var_tab = _ref[2], renderPacks = _ref[3], renderArbor = _ref[4], looping = _ref[5], debug = _ref[6], infobox = _ref[7], tags = _ref[8], id = _ref[9], delta = _ref[10];

  ALPHABET = "abcdefghijklmnopqrstuvwxyz?";

  CSS_COLOR_NAMES = ["Blue", "Brown", "BurlyWood", "CadetBlue", "Chartreuse", "Chocolate", "Coral", "Yellow", "Crimson", "Cyan", "DarkBlue", "DarkCyan", "DarkGoldenRod", "DarkGray", "DarkGreen", "DarkKhaki", "DarkMagenta", "DarkOliveGreen", "Darkorange", "DarkOrchid", "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue", "DarkSlateGrey", "DeepPink", "White", "DimGray", "DimGrey", "DodgerBlue", "FireBrick", "FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite", "Gold", "GoldenRod", "Gray", "Grey", "Green", "GreenYellow", "HoneyDew", "HotPink", "IndianRed", "Indigo", "Ivory", "Khaki", "Lavender", "LavenderBlush", "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral", "LightCyan", "LightGoldenRodYellow", "LightGray", "LightGrey", "LightGreen", "LightPink", "LightSalmon", "LightSeaGreen", "LightSkyBlue", "LightSlateGray", "LightSlateGrey", "LightSteelBlue", "LightYellow", "Lime", "LimeGreen", "Linen", "Magenta", "Maroon", "MediumAquaMarine", "MediumBlue", "MediumOrchid", "MediumPurple", "MediumSeaGreen", "MediumSlateBlue", "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "MidnightBlue", "MintCream", "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace", "Olive", "OliveDrab", "Orange", "OrangeRed", "Orchid", "PaleGoldenRod", "PaleGreen", "PaleTurquoise", "PaleVioletRed", "PapayaWhip", "PeachPuff", "Peru", "Pink", "Plum", "PowderBlue", "Purple", "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon", "SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver", "SkyBlue", "SlateBlue", "SlateGray", "SlateGrey", "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato", "Turquoise", "Violet", "Wheat", "White", "WhiteSmoke", "YellowGreen"];

  FUNCTION = {
    "ZERO": "(λf.λx.x)",
    "ONE": "(λf.λx.(f x))",
    "TWO": "(λf.λx.(f(f x)))",
    "THREE": "(λf.λx.(f(f(f x))))",
    "FOUR": "(λf.λx.(f(f(f(f x)))))",
    "FIVE": "(λf.λx.(f(f(f(f(f x))))))",
    "SIX": "(λf.λx.(f(f(f(f(f(f x)))))))",
    "SUCC": "(λn.λf.λx.f (n f x))",
    "PLUS": "(λm.λn.λf.λx.m f (n f x))",
    "MULT": "(λm.λn.λf.m (n f))",
    "POW": "(λb.λe.e b)",
    "PRED": "(λa.λf.λx.a (λg.λh.h (g f)) (λu.x) (λu.u))",
    "SUB": "(λm.λa. (a  (λn.λf.λx. n (λg.λh.h (g f)) (λu.x) (λu.u))) m)",
    "TRUE": "(λa.λb.a)",
    "FALSE": "(λa.λb.b)",
    "AND": "(λp.λq.p q p)",
    "OR": "(λp.λq.p p q)",
    "NOT": "(λp.λa.λb.p b a)",
    "IF": "(λp.λa.λb.p a b)",
    "ISZERO": "(λn.n (λx.(λa.λb.b)) (λa.λb.a))",
    "LEQ": "(λc.λp. (λq.q (λx.(λd.λe.e)) (λd.λe.d)) ((λm.λa. (a  (λn.λf.λx. n (λg.λh.h (g f)) (λu.x) (λu.u))) m) c p))",
    "Y": "(λf.( λx.( f (x x ) ) λx.( f (x x ) ) ) ) ",
    "FACT": "(λn.λf. (n (λc.λi. (i (c (λf.λx (i f (f x))))))(λx. f) (λx. x)))",
    "PAIR": "(λx.λy.λz.z x y)",
    "FIRST": "(λp.p (λx.λy.x))",
    "SECOND": "(λp.p (λx.λy.y))",
    "NIL": "((λx.λy.λz.z x y) (λa.λb.a) (λa.λb.a))",
    "ISNIL": "(λp.p (λx.λy.x))",
    "CONS": "(λh.λt. (λx.λy.λz.z x y) (λa.λb.b) ((λx.λy.λz.z x y) h t))",
    "HEAD": "(λz. (λp.p (λx.λy.x)) ((λp.p (λx.λy.y)) z))",
    "TAIL": "(λz. (λp.p (λx.λy.y)) ((λp.p (λx.λy.y)) z))"
  };

  EXERCICES = {
    "a": {
      "titre": 'Les items : "Le vieil alligator & les œufs"',
      "texte": "<p>Voilà un vieil alligator avec des œufs ! Le vieil alligator n'a plus faim, il a assez mangé.</p><p>Tous ce qu'il fait, c'est prendre soin de sa famille : ici ce sont des œufs et un autre vieil alligator qui garde deux oeufs!</p><p>Les œufs vont éclore et donner de nouvelles familles d'alligators.</p><p>Fais glisser un vieil alligator dans le panel, puis fais glisser le premier œuf sur le bout de la queue. Enfin, un à un, glisse des œufs et le vieil alligator les uns sur les autres pour les ajouter !</p>",
      "contenu-exercice": "(f g h (i i) )",
      "contenu-eleve": "(?)",
      "compte-rendu": "()",
      "solution": "(f g h (i i) ) "
    },
    "b": {
      "titre": 'Les items : "Les alligators affamés"',
      "texte": "<p>Voilà des alligators affamés...Les alligators affamés sont voraces. Ils vont manger tout ce qui est en devant eux (au point de mourir d'indigestion)! Mais ils sont aussi des alligators responsables, et comme les vieux alligators, ils gardent leurs familles.</p><p>Allez fais glisser !</p>",
      "contenu-exercice": "λx.(λy.(λz.() ) ) ",
      "contenu-eleve": "λx.()",
      "compte-rendu": "λ?",
      "solution": "λx.(λy.(λz.() ) ) "
    },
    "c": {
      "titre": 'Les familles (1)',
      "texte": "<p>Voici une petite famille : un alligator garde son œuf !</p><p>Peux tu la recréer ?</p>",
      "contenu-exercice": "λe.e",
      "contenu-eleve": "",
      "compte-rendu": "λ?",
      "solution": "λe.(e ) "
    },
    "d": {
      "titre": 'Les familles (2)',
      "texte": "<p>Voici une petite famille un peu plus grande.</p><p>Un alligator garde un autre alligator qui garde deux œufs. Ou on peut dire qu'un alligator garde un autre alligator qui est gardien des deux œufs.</p><p>Peux tu la recréer ?</p>",
      "contenu-exercice": "λe.λf.e f",
      "contenu-eleve": "",
      "compte-rendu": "λ?",
      "solution": "λe.(λf.(e f ) ) "
    },
    "e": {
      "titre": 'Les familles (3)',
      "texte": "<p>Voici une grande famille ! Nous avons un alligator jaune, un vert et un rose qui gardent cette famille. Ils gardent trois choses : un œuf vert, un vieux crocodile , et un œuf rose. Le vieil alligator, lui, garde un œuf jaune et un œuf vert.</p><p>Note bien que les œufs n'utilisent que les couleurs des alligators qui les surveillent . On ne peut pas avoir un œuf bleu sans qu'il y ait un alligator bleu au-dessus pour le garder.</p><p>Peux recréer cette famille ?</p>",
      "contenu-exercice": "λh.λe.λg.(e (h e) g)",
      "contenu-eleve": "λh.λe.λg.?",
      "compte-rendu": "λ?. ",
      "solution": "λh.(λe.(λg.(e (h e ) g ) ) ) "
    },
    "f": {
      "titre": 'Manger',
      "texte": "<p>Attention, ça va se compliquer !</p><p>Voici deux familles, l'une à coté de l'autre. L'alligator vert est affamé, et il y a cette famille jaune juste en face de lui... Comme elle semble appétissante! La suite, tu la connais ?! Appuye sur le bouton (&#9658;).</p><p>Malheureusement , les yeux du crocodile vert étaient plus grands que son ventre. Il trop a mangé ! En mourant, il s'en va au paradis des alligator (ouf !). Mais, l'histoire ne se arrête pas là ; parce qu'une fois l'alligator vert mort, l'oeuf vert commence à éclore... Et étonnamment, il éclot exactement en ce que l'alligator vert avait mangé. C'est le miracle de la vie ! Maintenant, nous avons une nouvelle famille: un crocodile rouge gardant un alligator jaune et un oeuf rouge, et l'alligator jaune qui garde son œuf jaune. Mais cet alligator jaune à faim , et il y a un bel œuf rouge en face de lui. On y va encore une fois (&#9658;).</p><p>Pauvre alligator. Même un seul œuf est trop gros pour son estomac! L'alligator jaune meurt... mais encore une fois , l'œuf jaune commence à éclore ...Et il éclot dans exactement ce que l'alligator jaune avait mangé !</p><p>Maintenant, il n'y a plus rien pour quiconque à manger, donc nous pouvons arrêter là.</p>",
      "contenu-exercice": "λe.(λf.(e f ) ) λh.(h ) ",
      "contenu-eleve": "",
      "solution": "",
      "animation": "yes"
    },
    "g": {
      "titre": 'La règle du "je te mange"',
      "texte": "<p>La règle de l'alimentation dit que s'il y a des familles côte-à-côté, l'alligator le plus en haut à gauche de la famille mange à sa droite.Puis , ce crocodile meurt . Mais si il gardait des oeufs de la même couleur que lui, chacun de ces oeufs va éclorent en ce qu'il a mangé</p>.<p>En continuant, l'alligator orange, mange la famille jaune. Ensuite, l'alligator vert en haut à gauche veut manger la famille à sa droite. Mais avant qu'elle ne puisse le faire , nous devons nous pencher sur la règle de couleur !</p><p>La règle de couleur dit que si un alligator est sur ​​le point de manger une famille, et que s'il y a une couleur qui apparaît dans les deux familles, nous devons changer cette couleur dans une famille avec une autre couleur. Ici, vert et rouge apparaissent à la fois la première et la seconde famille. Le changement de couleur est automatique. Une fois qu'ils ne partagent plus les mêmes couleurs, nous pouvons manger! Et manger!Et manger! Et manger, jusqu'à ce qu'il n'y ai rien de plus qui puisse être mangé .</p>",
      "contenu-exercice": "λz.(λe.(z z e ) ) λe.(λf.(e f ) ) λh.(h ) ",
      "contenu-eleve": "",
      "solution": "",
      "animation": "yes"
    },
    "h": {
      "titre": 'La règle du vieil alligator',
      "texte": "<p>Il ne reste plus qu'une seule règle dans ce jeu, et elle est en lien avec les vieux alligators :</p><p>L'alligator supérieur gauche ici n'a pas faim. Il ne va rien manger du tout. Tout ce dont il se soucie est sa famille. Alors, comment meurt-il?</p><p>Il meurt quand il garde seulement une seule chose. À l'heure actuelle, Il est à la fois gardien d'une famille verte et d'une famille rouge. Ils ont besoin de lui pour prendre soin d'eux. Mais l'alligator vert a faim: il mange la famille rouge ...</p><p>Maintenant , le vieux crocodile ne garde plus qu'une seule famille. Cette famille peut prendre soin d'elle-même. Il n'est par conséquent plus nécessaire. Donc , il vieillit et meurt: C'est la vieille règle de l'âge!</p><p>Lorsque un vieux crocodile est juste gardait une seule chose , il meurt.</p><p>Pour finir, l'alligator rouge mange la famille jaune, et il ne reste plus rien qui puisse être mangé.</p>",
      "contenu-exercice": "(λe.(e ) λf.(f ) ) λe.(e ) ",
      "contenu-eleve": "",
      "solution": "",
      "animation": "yes"
    },
    "i": {
      "titre": 'Challenge !',
      "texte": "<p>Voici deux familles. Elles s'appellent «Vrai» et «Faux» :</p><insert λe.(λf.(e ) ) λe.(λf.(f ) ) ><p>Et ici, une famille appelée «Non» : <insert λh.(h λe.(λf.( ? ) ) λe.(λf.( ? ) ) ) ></p><p>Lorsque «Non» mange «Vrai», il produit «Faux». Et lorsque «Non» mange «Faux», il produit «Vrai». De quelles couleurs devraient être les deux œufs?</p>",
      "contenu-exercice": "",
      "contenu-eleve": "λh.(h λe.(λf.( ? ) ) λe.(λf.( ? ) ) ) (λe.λf.?) ",
      "compte-rendu": "λh.(h λe.(λf.( ? ) ) λe.(λf.( ? ) ) ) ",
      "solution": "λh.(h λe.(λf.( f ) ) λe.(λf.( e ) ) ) ",
      "parse": "yes"
    }
  };

  $(function() {
    var circle_pack_drawing, color, color_rule_check, create_edges_for_heritier, draw_lambda_expression, egg_def, find_action_pointer, get_lambda_from, go_one_step, help, index, inserer, insert_exp_into_div, insert_item, key, letter, make_dropped_droppable, open_def, parse, preparer_exercice, render_viewport, resize, sys, transform_div_to_node, value, _i, _j, _len, _len1;
    for (index = _i = 0, _len = ALPHABET.length; _i < _len; index = ++_i) {
      letter = ALPHABET[index];
      color_tab.push(CSS_COLOR_NAMES[index]);
      var_tab["" + letter] = CSS_COLOR_NAMES[index];
    }
    for (key in EXERCICES) {
      $("#exercices").append("<option value='" + key + "'  data-id='" + key + "'>Exercice " + key + "</button>");
    }
    for (key in FUNCTION) {
      value = FUNCTION[key];
      $("#console").append("<button id='" + key + "' class='panel-button' data-type='fonction' data-lambda='" + value + "'>" + key + "</button>");
    }
    for (index = _j = 0, _len1 = color_tab.length; _j < _len1; index = ++_j) {
      color = color_tab[index];
      $("#choose-color").append("<option value='" + ALPHABET[index] + "' data-color='" + color + "' data-class='ui-icon-script' >" + ALPHABET[index] + "</option>");
    }
    open_def = $.Deferred();
    egg_def = $.Deferred();
    $.get("css/svg/egg.svg", function(rawSvg) {
      $(".item#egg-svg").append(document.importNode(rawSvg.documentElement, true));
      $(".item#egg-svg svg")[0].setAttribute('viewBox', '0 0 118 80');
      return egg_def.resolve();
    }, "xml");
    $.get("css/svg/open.svg", function(rawSvg) {
      $(".item#open-svg").append(document.importNode(rawSvg.documentElement, true));
      $(".item#open-svg svg")[0].setAttribute('viewBox', '0 0 300 124');
      return open_def.resolve();
    }, "xml");
    $.get("css/svg/vieux.svg", function(rawSvg) {
      $(".item#vieux-svg").append(document.importNode(rawSvg.documentElement, true));
      return $(".item#vieux-svg svg")[0].setAttribute('viewBox', '0 0 300 124');
    }, "xml");
    sys = arbor.ParticleSystem();
    sys.parameters({
      repulsion: 2600,
      stiffness: 1000,
      friction: 0,
      gravity: false,
      precision: 0.015
    });
    sys.renderer = Renderer("#viewport");
    sys.stop();
    $.when(open_def, egg_def).done(function() {
      return $("#choose-color").trigger("selectmenuchange");
    });
    resize = function() {
      var double, s, simple, _ref1;
      value = parseInt($("#amount-zoom").html());
      _ref1 = ["" + value + "px", "" + (2 * value) + "px"], simple = _ref1[0], double = _ref1[1];
      s = ".lambda.priorite.dropped, .lambda.dropped { \n  min-width  : " + double + ";\n  min-height : " + simple + ";\n  padding-top: " + simple + ";\n}\n.variable.dropped { \n  width  : " + double + ";\n  height : " + simple + ";\n}\n.dropped .svg-container {\n  height : " + simple + ";\n}\n.definition_drop, .application_drop {\n  width : " + simple + ";\n  height: " + simple + ";\n}";
      return $("#restyler").text(s);
    };
    $.widget("ui.selectmenu", $.extend({}, $.ui.selectmenu.prototype, {
      _renderItem: function(ul, item) {
        var li, s;
        color = var_tab[item.value];
        li = $("<li>").css("background-color", color);
        s = "position:absolute;top:2%;left:2%;width:96%; height:96%;color:black;background:" + color + ";border-radius:100%;";
        $("<span>", {
          text: item.value,
          style: s
        }).appendTo(li);
        return li.appendTo(ul);
      },
      _renderMenu: function(ul, items) {
        var that;
        that = this;
        return $.each(items, function(index, item) {
          that._renderItemData(ul, item);
          return $("#color").css("background", item.element.attr("data-color")).attr("data-variable", item.value).attr("data-color", item.element.attr("data-color"));
        });
      }
    }));
    $("#choose-color").selectmenu({
      appendTo: "#command-panel",
      open: function() {
        return $("#game-container").addClass("stop-scrolling");
      },
      close: function() {
        return $("#game-container").removeClass("stop-scrolling");
      }
    }).on("selectmenuchange", function(event, ui) {
      var variable, _ref1, _ref2;
      if (ui != null) {
        _ref1 = [ui.item.element.attr("data-color"), ui.item.value], color = _ref1[0], variable = _ref1[1];
      } else {
        _ref2 = ["Blue", "a"], color = _ref2[0], variable = _ref2[1];
      }
      $("#panel-lambda").attr("data-variable", variable).html("λ" + variable);
      $("#panel-variable").attr("data-variable", variable).html("" + variable);
      $(".item#egg-svg > svg, .item#open-svg > svg").find(".skin").css("fill", color);
      return $("#color").css("background", color).attr("data-variable", variable).attr("data-color", color);
    });
    $("#exercices").selectmenu({
      appendTo: "#top-panel"
    }).on("selectmenuchange", function(event, ui) {
      var i;
      i = ui.item.element.attr("data-id");
      $("#replay").attr("data-id", i);
      return preparer_exercice(i);
    });
    $("#slider-repulsion").slider({
      range: "max",
      min: 1,
      max: 3000,
      step: 10,
      value: 2000,
      slide: function(event, ui) {
        $("#amount-repulsion").html(ui.value);
        return sys.parameters({
          repulsion: ui.value
        });
      }
    });
    $("#amount-repulsion").html("2000");
    $("#slider-stiffness").slider({
      range: "max",
      min: 1,
      max: 3000,
      step: 10,
      value: 1000,
      slide: function(event, ui) {
        $("#amount-stiffness").html(ui.value);
        return sys.parameters({
          stiffness: ui.value
        });
      }
    });
    $("#amount-stiffness").html("1000");
    $("#slider-friction").slider({
      range: "max",
      min: 0,
      max: 1,
      step: 0.1,
      value: 0,
      slide: function(event, ui) {
        $("#amount-friction").html(ui.value);
        return sys.parameters({
          friction: ui.value
        });
      }
    });
    $("#amount-friction").html("0");
    $("#slider-zoom").slider({
      range: "max",
      min: 1,
      max: 100,
      step: 1,
      value: 40,
      slide: function(event, ui) {
        $("#amount-zoom").html(ui.value);
        return resize();
      }
    });
    $("#amount-zoom").html("40");
    resize();
    $("#slider-animation").slider({
      range: "max",
      min: 20,
      max: 6000,
      step: 20,
      value: 2000,
      slide: function(event, ui) {
        $("#amount-animation").html(ui.value);
        return delta = ui.value;
      }
    });
    $("#amount-animation").html($("#slider-animation").slider("value"));
    $("#console button").button();
    $('#close-console').button({
      text: false,
      icons: {
        primary: 'ui-icon-close'
      }
    });
    $('#play').button({
      text: false,
      icons: {
        primary: 'ui-icon-play'
      }
    });
    $('#stop').button({
      text: false,
      icons: {
        primary: 'ui-icon-stop'
      }
    });
    $('#forward').button({
      text: false,
      icons: {
        primary: 'ui-icon-seek-next'
      }
    });
    $('#clear').button({
      text: false,
      icons: {
        primary: 'ui-icon-trash'
      }
    });
    $('#toggle-settings').button({
      text: false,
      icons: {
        primary: 'ui-icon-wrench'
      }
    });
    $('#tags').button({
      text: false,
      icons: {
        primary: 'ui-icon-tag'
      }
    });
    $('#infobox').button({
      text: false,
      icons: {
        primary: 'ui-icon-comment'
      }
    });
    $('#toggle-console').button({
      text: false,
      icons: {
        primary: 'ui-icon-calculator'
      }
    });
    $('#toggle-theory').button({
      text: false,
      icons: {
        primary: 'ui-icon-script'
      }
    });
    $('#toggle-graph').button({
      text: false,
      icons: {
        primary: 'ui-icon-image'
      }
    });
    $("#layout").buttonset();
    $("#croco-layout").on("click", function() {
      sys.stop();
      renderArbor = renderPacks = false;
      $("#viewport, #chart, #toggle-graph-settings").hide();
      return $("#panels,  #toggle-croco-settings").show();
    });
    $("#packs-layout").on("click", function() {
      sys.stop();
      renderArbor = false;
      renderPacks = true;
      $("#viewport, #panels, #toggle-croco-settings, #toggle-graph-settings").hide();
      return $("#chart").show();
    });
    $("#graph-layout").on("click", function() {
      renderArbor = true;
      renderPacks = false;
      render_viewport().init($("#root"));
      $("#panels, #chart, #toggle-croco-settings").hide();
      return $("#viewport, #toggle-graph-settings").show();
    });
    $("#toggle-croco-settings").on("click", function() {
      return $("#croco-settings").toggle();
    });
    $("#toggle-graph-settings").on("click", function() {
      return $("#graph-settings").toggle();
    });
    $("#croco-settings, #graph-settings").toggle();
    $("#toggle-console").on("click", function() {
      return $("#console").toggle();
    });
    $("#close-console").on("click", function() {
      return $("#console").toggle();
    });
    $("#infobox").on("click", function() {
      return infobox = !infobox;
    });
    $("#tags").on("click", function() {
      var selection, _ref1;
      _ref1 = [$(".variable.dropped, .lambda.dropped"), !tags], selection = _ref1[0], tags = _ref1[1];
      if (tags) {
        return selection.addClass("show_pseudo");
      } else {
        return selection.removeClass("show_pseudo");
      }
    });
    $("#packs-layout").trigger("click");
    $(".item").draggable({
      helper: "clone",
      start: function(event, ui) {
        return $(ui.helper).addClass("ui-draggable-helper");
      },
      stop: function(event, ui) {
        return $(this).show();
      }
    });
    $(".panel-button").on("click", function() {
      var parentheses, _k, _len2, _ref1, _results;
      switch ($(this).attr("data-type")) {
        case "lambda":
          return $("#prompt").val($("#prompt").val() + ("λ" + ($(this).attr('data-variable')) + "."));
        case "variable":
          return $("#prompt").val($("#prompt").val() + (" " + ($(this).attr('data-variable')) + " "));
        case "open":
          return $("#prompt").val($("#prompt").val() + "(");
        case "close":
          return $("#prompt").val($("#prompt").val() + ")");
        case "fonction":
          return $("#prompt").val($("#prompt").val() + " " + $(this).attr("data-lambda"));
        case "read":
          return $("#prompt").val(get_lambda_from($("#root")));
        case "draw":
          return draw_lambda_expression($("#prompt").val());
        case "stop":
          looping = false;
          return $(".animation").prop("disabled", false);
        case "play":
          $(".animation").prop("disabled", true);
          looping = false;
          $(".animation").prop("disabled", true);
          $("#root .application_drop, #root .definition_drop").remove();
          return go_one_step("#root");
        case "forward":
          $(".animation").prop("disabled", true);
          $("#root .application_drop, #root .definition_drop").remove();
          looping = true;
          return go_one_step("#root");
        case "clear":
          looping = false;
          $("#root").empty().append("<div id='root_definition' class='definition_drop'></div>");
          $("#prompt").val("");
          sys.eachNode(function(node) {
            return sys.pruneNode(node);
          });
          return make_dropped_droppable();
        case "autoclose":
          parentheses = 0;
          _ref1 = $("#prompt").val();
          for (index = _k = 0, _len2 = _ref1.length; _k < _len2; index = ++_k) {
            letter = _ref1[index];
            switch (letter) {
              case "(":
                parentheses += 1;
                break;
              case ")":
                parentheses -= 1;
            }
          }
          if (parentheses < 0) {
            return alert("il y a " + parentheses + " parenthese(s) fermée en trop !)");
          } else {
            _results = [];
            while (parentheses > 0) {
              $("#prompt").val($("#prompt").val() + ")");
              _results.push(parentheses -= 1);
            }
            return _results;
          }
      }
    });
    draw_lambda_expression = function(expression) {
      insert_exp_into_div(expression, $("#root"));
      sys.eachNode(function(node) {
        return sys.pruneNode(node);
      });
      if (renderArbor) {
        render_viewport().init($("#root"));
      }
      return circle_pack_drawing('chart');
    };
    $("#help").dialog({
      autoOpen: false,
      dialogClass: "noTitleStuff",
      width: "auto",
      minHeight: 0,
      open: function(event, ui) {
        return delay(1000, function() {
          return $("#help").dialog("close");
        });
      },
      autoResize: true
    });
    help = function(message, element) {
      $("#help").dialog("option", {
        position: {
          my: "center bottom",
          at: "center top",
          of: "#" + element
        }
      });
      $("#help").html(message);
      return $("#help").dialog("open");
    };
    $("#console").draggable({
      containment: "#game-container"
    }).toggle();
    $("#command-panel").draggable({
      containment: "#game-container"
    });
    preparer_exercice = function(id) {
      var exo, lambda, reg, texte;
      $(".animation").prop("disabled", false);
      exo = EXERCICES[id];
      $("#replay").attr("data-id", id);
      $("#exercice").attr("data-solution", exo["solution"]);
      $("#exercice").find("> .titre").html("<h1>" + exo['titre'] + "</h1>");
      if (exo["contenu-eleve"] !== "") {
        insert_exp_into_div(exo["contenu-eleve"], $("#root"));
      } else {
        $("#root").empty().append("<div id='root_definition' class='definition_drop'></div>");
      }
      if (exo["contenu-exercice"] !== "") {
        insert_exp_into_div(exo["contenu-exercice"], $("#contenu-exercice"));
      }
      if (exo["animation"] === "yes") {
        $("#animation").show();
      } else {
        $("#animation").hide();
      }
      texte = exo['texte'];
      reg = /<insert ([λ().\w\? ]*)>/;
      while (texte.match(reg)) {
        lambda = reg.exec(texte);
        insert_exp_into_div(lambda[1], $("#exercice-texte"));
        texte = texte.replace(reg, $("#exercice-texte").html());
      }
      $("#exercice-texte").html("<p>" + texte + "</p>");
      if ("compte-rendu" in exo) {
        texte = exo["compte-rendu"];
        insert_exp_into_div(texte, $("#compte-rendu"));
      }
      return $("#exercice").show();
    };
    $("#exercice").hide();
    $("#close-exercice").on("click", function() {
      return $("#exercice").hide();
    });
    $("#replay").on("click", function() {
      return preparer_exercice($(this).attr("data-id"));
    });
    $("#animation").on("click", function(event) {
      $(".animation").prop("disabled", true);
      $("#contenu-exercice .application_drop, #contenu-exercice .definition_drop").remove();
      return go_one_step("#contenu-exercice");
    });
    $("#exercice .check").on("click", function() {
      var local_debug, resultat, solution;
      local_debug = true;
      solution = $("#exercice").attr("data-solution");
      resultat = get_lambda_from($("#compte-rendu"));
      if (resultat === solution) {
        return alert("Super ! Si tu as tout compris, passe à l'exo suivant. Sinon rejoue !");
      } else {
        return alert("Raté ! Essaye encore, n'oublie pas de cliquer sur 'rejouer'");
      }
    });
    $("#theory").toggle();
    $("#toggle-theory").on("click", function() {
      return $("#theory").toggle();
    });
    $(".run-previous-code").on("click", function() {
      var js;
      js = CoffeeScript.compile($(this).prev(":first").text());
      return eval(js);
    });
    parse = function($el) {
      var result;
      result = {};
      result['name'] = $el.attr('id');
      if ($el.attr('data-color') != null) {
        result['color'] = $el.attr('data-color');
      } else {
        result['color'] = 'white';
      }
      if ($el.children('.dropped').length > 0) {
        result['children'] = [];
        $el.children(".dropped").each(function(i, e) {
          return result['children'].push(parse($(this)));
        });
      } else {
        result['size'] = 1;
      }
      return result;
    };
    circle_pack_drawing = function(div_id) {
      var format, h, json, node, pack, vis, w;
      w = 960;
      h = 960;
      format = d3.format(',d');
      pack = d3.layout.pack().size([w - 4, h - 4]).value(function(d) {
        return d.size;
      });
      $("#" + div_id).empty();
      vis = d3.select("#" + div_id).append('svg:svg').attr('width', w).attr('height', h).attr('class', 'pack').append('svg:g').attr('transform', 'translate(2, 2)');
      json = parse($(root));
      node = vis.data([json]).selectAll('g.node').data(pack.nodes).enter().append('svg:g').attr('class', function(d) {
        if (d.children) {
          return 'node';
        } else {
          return 'leaf node';
        }
      }).attr('transform', function(d) {
        return 'translate(' + d.x + ',' + d.y + ')';
      }).style('fill', function(d) {
        return d.color;
      });
      node.append('svg:title').text(function(d) {
        return d.name + (d.children ? '' : ': ' + format(d.size));
      });
      node.append('svg:circle').attr('r', function(d) {
        return d.r;
      });
      return node.filter(function(d) {
        return !d.children;
      }).append('svg:text').attr('text-anchor', 'middle').attr('dy', '.3em').text(function(d) {
        return d.name.substring(0, d.r / 3);
      });
    };
    insert_item = function(element) {
      var variable;
      if ((element.hasClass("lambda")) && (element.hasClass("priorite"))) {
        $(".item#vieux-svg").clone().removeClass("item").prependTo(element);
      } else {
        variable = element.attr("data-variable");
        element.attr("data-color", "" + var_tab[variable]);
        if (element.hasClass("variable")) {
          $(".item#egg-svg > svg").find(".skin").css("fill", element.attr("data-color"));
          $(".item#egg-svg ").clone().removeClass("item").prependTo(element);
        } else {
          $(".item#open-svg > svg").find(".skin").css("fill", element.attr("data-color"));
          $(".item#open-svg").clone().removeClass("item").prependTo(element);
        }
      }
      if (variable === "?") {
        return element.addClass("definition_dropped");
      }
    };
    get_lambda_from = function(root) {
      var exp;
      exp = root.clone();
      exp.find("svg, .svg-container, .definition_drop, .application_drop").remove();
      exp = exp.html();
      exp = exp.replace(/<div(?: style="[\w \;\:\-]*")? id="\d*" class="variable[\w \_\-]*" data-variable="([\w\?])" data-color="\w+"(?: style="[\w \;\:\-]*")?>\s*<\/div>/g, "$1 ");
      exp = exp.replace(/<div(?: style="[\w \;\:\-]*")? id="\d*" class="lambda[\w \_\-]*" data-variable="([\w\?])" data-color="\w+"(?: style="[\w \;\:\-]*")?>/g, "λ$1.(");
      exp = exp.replace(/<div(?: style="[\w \;\:\-]*")? id="\d*" class="lambda priorite[\w \_\-]*" data-variable="\(" data-color="white"(?: style="[\w \;\:\-]*")?>/g, "(");
      exp = exp.replace(/<\/div>/g, ") ");
      return exp = exp.replace(/\s{2,}/g, " ");
    };
    insert_exp_into_div = function(exp, root) {
      var current_index, expression, local_debug, parentheses, reg, λ_index, λ_variable;
      expression = exp;
      id = 0;
      expression = expression.replace(/([.( ])(([\w\?]))/g, "$1woot$2");
      local_debug = false;
      while (expression.match(/λ/)) {
        λ_index = 0;
        while (expression[λ_index] !== "λ") {
          λ_index += 1;
        }
        λ_variable = λ_index + 1;
        current_index = λ_index + 3;
        switch (expression[λ_index - 1]) {
          case "(":
            if (local_debug) {
              alert("prototype : (λx. lambda ) = " + expression);
            }
            parentheses = 1;
            while ((parentheses > 0) && (current_index < expression.length) && (expression[current_index] !== "<")) {
              switch (expression[current_index]) {
                case "(":
                  parentheses += 1;
                  break;
                case ")":
                  parentheses -= 1;
              }
              current_index += 1;
            }
            if (local_debug) {
              alert("I got this : " + (expression.substring(λ_index - 1, current_index)));
            }
            expression = expression.replace(expression.substring(λ_index - 1, current_index), "<div id='' class='lambda dropped' data-variable='" + expression[λ_variable] + "' data-color=''>" + (expression.substring(λ_index + 3, current_index - 1)) + "</div>");
            continue;
          default:
            switch (expression[current_index]) {
              case "(":
                if (local_debug) {
                  alert("prototype : λx.(lambda) = " + expression);
                }
                parentheses = 1;
                while ((parentheses > 0) && (current_index < expression.length) && (expression[current_index] !== "<")) {
                  current_index += 1;
                  switch (expression[current_index]) {
                    case "(":
                      parentheses += 1;
                      break;
                    case ")":
                      parentheses -= 1;
                  }
                }
                if (local_debug) {
                  alert("I got this : " + (expression.substring(λ_index, current_index + 1)));
                }
                expression = expression.replace(expression.substring(λ_index, current_index + 1), "<div id='' class='lambda dropped' data-variable='" + expression[λ_variable] + "' data-color=''>" + (expression.substring(λ_index + 4, current_index)) + "</div>");
                continue;
              default:
                if (local_debug) {
                  alert("prototype : λx.lambda = " + expression);
                }
                while ((expression[current_index] !== "<") && (current_index < expression.length)) {
                  current_index += 1;
                }
                if (local_debug) {
                  alert("I got this : " + (expression.substring(λ_index, current_index)));
                }
                expression = expression.replace(expression.substring(λ_index, current_index), "<div id='' class='lambda dropped' data-variable='" + expression[λ_variable] + "' data-color=''>" + (expression.substring(λ_index + 3, current_index)) + "</div>");
                continue;
            }
        }
      }
      expression = expression.replace(/[ ]*\(([^)]*\s?\)*)\)[ ]*/g, "<div id='' class='lambda priorite dropped' data-variable='parenthese' data-color='white' >$1</div>");
      expression = expression.replace(/\(/g, "<div id='' class='lambda priorite dropped' data-variable='parenthese' data-color='white'>");
      expression = expression.replace(/\)/g, "</div>");
      expression = expression.replace(/parenthese/g, "(");
      reg = /woot([\w\?])/g;
      expression = expression.replace(reg, "<div id='' class='variable dropped' data-variable='$1' data-color='' ></div>");
      expression = $('<div/>').html(expression).contents();
      root.empty().append($(expression));
      $(root).find(".dropped").each(function() {
        $(this).attr("id", "" + (id += 1));
        return insert_item($(this));
      });
      return make_dropped_droppable();
    };
    inserer = function(draggable, droppable) {
      var lambda, type, variable, _ref1, _ref2;
      if (draggable.hasClass("vieux-croco")) {
        _ref1 = ["(", "white"], variable = _ref1[0], color = _ref1[1];
      } else {
        _ref2 = [$("#color").attr("data-variable"), $("#color").attr("data-color")], variable = _ref2[0], color = _ref2[1];
      }
      if (draggable.hasClass("egg")) {
        type = "variable";
      } else if (draggable.hasClass("croco")) {
        type = "lambda";
      } else {
        type = "lambda priorite";
      }
      lambda = "<div id='" + (id++) + "' class='" + type + " dropped' data-variable='" + variable + "' data-color='" + color + "' ><div class='application_drop'></div></div>";
      lambda = $('<div/>').html(lambda).contents();
      if (type !== "variable") {
        $(lambda).prepend("<div class='definition_drop'></div>");
      }
      insert_item($(lambda));
      if (droppable.attr("data-variable") === "?") {
        droppable.find("> svg, > .svg-container").remove();
        droppable.after($(lambda));
        return droppable.remove();
      } else {
        if (droppable.hasClass("definition_drop")) {
          droppable.before($(lambda));
        } else {
          droppable.parent().after($(lambda));
        }
        return droppable.remove();
      }
    };
    make_dropped_droppable = function() {
      return $(".application_drop, .definition_drop, [data-variable='?']:not(#color)").droppable({
        hoverClass: "ui-state-hover",
        accept: ".item",
        drop: function(event, ui) {
          inserer(ui.draggable, $(this));
          return make_dropped_droppable();
        }
      });
    };
    make_dropped_droppable();
    find_action_pointer = function(root) {
      var local_debug, pointer, _ref1;
      _ref1 = [[], false], ahead_vars = _ref1[0], local_debug = _ref1[1];
      pointer = $(root).children(".lambda:first()");
      while (pointer.length > 0) {
        if (pointer.hasClass("priorite")) {
          if (pointer.children(".dropped").length === 1) {
            break;
          }
        } else {
          if (pointer.next().length > 0) {
            break;
          }
          ahead_vars.push(pointer.attr("data-variable"));
        }
        pointer = pointer.children(".lambda:first");
      }
      return pointer;
    };
    color_rule_check = function(pointer) {
      var application, application_vars, function_vars, get_vars, intersect, intersection, item, palette, _ref1;
      get_vars = function(tree) {
        var palette;
        palette = [];
        tree.find("[data-variable]").addBack().filter("[data-variable]").not(".lambda.priorite").each(function() {
          return palette.push($(this).attr("data-variable"));
        });
        return palette.unique();
      };
      intersect = function(a, b) {
        return a.filter(function(n) {
          return b.indexOf(n) !== -1;
        });
      };
      application = pointer.next();
      _ref1 = [get_vars(pointer), get_vars(application)], function_vars = _ref1[0], application_vars = _ref1[1];
      intersection = intersect(application_vars, function_vars);
      intersection = (function() {
        var _k, _len2, _results;
        _results = [];
        for (_k = 0, _len2 = intersection.length; _k < _len2; _k++) {
          item = intersection[_k];
          if (__indexOf.call(ahead_vars, item) < 0) {
            _results.push(item);
          }
        }
        return _results;
      })();
      palette = (function() {
        var _k, _len2, _ref2, _results;
        _ref2 = ALPHABET.slice(0, 25);
        _results = [];
        for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
          item = _ref2[_k];
          if (__indexOf.call(function_vars.concat(application_vars), item) < 0) {
            _results.push(item);
          }
        }
        return _results;
      })();
      palette = palette.slice(0, +(intersection.length - 1) + 1 || 9e9);
      return [intersection, palette];
    };
    create_edges_for_heritier = function(heritier) {
      var local_debug, next, parent, source, target;
      if (heritier.length > 0) {
        local_debug = false;
        if (local_debug) {
          console.log("CREATION DES LIENS POUR " + (heritier.attr('id')));
        }
        target = heritier.attr("id");
        next = heritier.next(".dropped");
        if (next.length > 0) {
          sys.addEdge(next.attr("id"), target, {
            type: "arrow",
            directed: true,
            color: "white",
            weight: 1
          });
          if (local_debug) {
            console.log(next.attr("id") + " next-> " + target);
          }
        }
        parent = heritier.parent();
        source = parent.attr("id");
        if ((source !== "root") && (source != null)) {
          sys.addEdge(source, target, {
            type: "arrow",
            directed: true,
            color: "grey",
            weight: 3
          });
          if (local_debug) {
            return console.log(parent.attr("id") + " parent-> " + target);
          }
        }
      }
    };
    transform_div_to_node = function(div) {
      var alias, label, mass, variable, _ref1, _ref2;
      if (div.hasClass("variable")) {
        _ref1 = ["                         ", div.attr("data-variable"), div.attr("data-color"), 1], alias = _ref1[0], variable = _ref1[1], color = _ref1[2], mass = _ref1[3];
      } else {
        _ref2 = ["", div.attr("data-variable"), div.attr("data-color"), 1], alias = _ref2[0], variable = _ref2[1], color = _ref2[2], mass = _ref2[3];
      }
      label = "" + alias;
      return sys.addNode(div.attr("id"), {
        'color': color,
        'shape': 'dot',
        'label': label,
        'mass': mass
      });
    };
    render_viewport = function() {
      return {
        init: function(pointer) {
          var branch, local_debug, particles;
          local_debug = true;
          if (local_debug) {
            console.log("init");
          }
          particles = $("#root").find(".dropped");
          if (particles.length > 0) {
            branch = {
              nodes: {},
              edges: []
            };
            particles.each(function() {
              transform_div_to_node($(this));
              return create_edges_for_heritier($(this));
            });
            find_action_pointer($("#root"));
          }
          return sys.start();
        }
      };
    };
    return go_one_step = function(root, button) {
      var action_croco, egg_fill_with, local_debug, make_generation_stuff, remove_app, step1, step2, step3, step4;
      local_debug = false;
      make_generation_stuff = function(div, deferred) {
        var t0, t1;
        if (deferred == null) {
          deferred = $.Deferred();
        }
        t0 = performance.now();
        if (infobox) {
          help("Partir", pointer.attr("id"));
        }
        $(div).children(".svg-container").remove();
        $(div).replaceWith($(div).contents());
        if (renderArbor) {
          $(root).find(".dropped").each(function() {
            return create_edges_for_heritier($(this));
          });
          sys.pruneNode($(div).attr("id"));
        }
        t1 = performance.now();
        console.log("make_generation_stuff: " + Math.floor(t1 - t0) + " ms");
        return deferred.resolve();
      };
      egg_fill_with = function(egg, application, index, n) {
        var appClone, app_id, edge, _k, _l, _len2, _len3, _ref1, _ref2;
        if (local_debug) {
          console.log("step 5 : ECLOSION DES OEUFS !");
        }
        switch (index) {
          case n - 1:
            appClone = application;
            if (renderArbor) {
              app_id = application.attr("id");
              _ref1 = sys.getEdgesFrom(app_id);
              for (_k = 0, _len2 = _ref1.length; _k < _len2; _k++) {
                edge = _ref1[_k];
                sys.pruneEdge(edge);
              }
              _ref2 = sys.getEdgesTo(app_id);
              for (_l = 0, _len3 = _ref2.length; _l < _len3; _l++) {
                edge = _ref2[_l];
                sys.pruneEdge(edge);
              }
            }
            break;
          default:
            appClone = application.clone();
            appClone.find(".dropped").addBack(".dropped").each(function() {
              return $(this).attr("id", id += 1);
            });
        }
        $(egg).append(appClone);
        if (renderArbor) {
          if (appClone.length > 0) {
            appClone.find(".dropped").addBack(".dropped").each(function() {
              return transform_div_to_node($(this));
            });
            $(egg).find(".dropped").each(function() {
              return create_edges_for_heritier($(this));
            });
          }
        }
        return make_generation_stuff($(egg));
      };
      remove_app = function(application) {
        if (infobox) {
          help("Aucun oeuf", "root");
        }
        if (renderArbor) {
          if (local_debug) {
            console.log("cas 2 : pas d'oeuf, on retire l'application, et le suivant est connecté");
          }
          application.find(".dropped").addBack().filter(".dropped").each(function() {
            return sys.pruneNode($(this).attr("id"));
          });
        }
        application.find("svg").remove();
        return application.remove();
      };
      step1 = $.Deferred();
      step2 = $.Deferred();
      step3 = $.Deferred();
      step4 = $.Deferred();
      step1.done(function(pointer) {
        if ((pointer.hasClass("priorite")) && (pointer.children(".dropped").length < 2)) {
          if (infobox) {
            help("Ce vieil alligator ne sert plus à rien !", pointer.attr("id"));
          }
          return make_generation_stuff(pointer, step2);
        } else {
          return step2.resolve();
        }
      });
      step2.done(function() {
        var application, intersection, letter_index, palette, pointer, selection, _k, _len2, _ref1, _results;
        pointer = find_action_pointer(root);
        _ref1 = color_rule_check(pointer), intersection = _ref1[0], palette = _ref1[1];
        if (intersection.length > 0) {
          if (infobox) {
            help("Règle de la couleur !", pointer.attr("id"));
          }
          application = pointer.next(".dropped");
          _results = [];
          for (letter_index = _k = 0, _len2 = intersection.length; _k < _len2; letter_index = ++_k) {
            letter = intersection[letter_index];
            selection = application.find("[data-variable='" + letter + "']").addBack("[data-variable='" + letter + "']");
            if (selection.length > 0) {
              _results.push(selection.each(function() {
                var new_var;
                new_var = palette[letter_index];
                color = var_tab[new_var];
                $(this).attr("data-variable", new_var);
                $(this).attr("data-color", color);
                $(this).find("> .svg-container .skin").css("fill", color);
                if (renderArbor) {
                  sys.tweenNode($(this).attr("id"), delta / 1000, {
                    color: color
                  });
                }
                circle_pack_drawing('chart');
                return delay(delta, function() {
                  return step3.resolve(pointer);
                });
              }));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        } else {
          return step3.resolve(pointer);
        }
      });
      step3.done(function(pointer) {
        var application, eggs, variable;
        if ((pointer.hasClass("lambda")) && (pointer.attr("data-color") !== "white") && (pointer.next().length > 0)) {
          if (infobox) {
            help("éclosion", "root");
          }
          variable = pointer.attr("data-variable");
          eggs = pointer.find(".variable.dropped[data-variable=" + variable + "]");
          application = pointer.next();
          switch (eggs.length) {
            case 0:
              remove_app(application);
              break;
            default:
              eggs.each(function(index, egg) {
                return egg_fill_with(egg, application, index, eggs.length);
              });
          }
          return make_generation_stuff(pointer, step4);
        } else {
          return step4.resolve();
        }
      });
      step4.done(function() {
        var edges, pointer;
        if (renderArbor) {
          pointer = find_action_pointer(root);
          if (pointer != null) {
            edges = sys.getEdgesTo(pointer.attr("id"));
            edges.forEach(function(edge) {
              return sys.tweenEdge(edge, delta / 1000, {
                weight: 10
              });
            });
          }
        }
        circle_pack_drawing('chart');
        return delay(delta, function() {
          if (looping) {
            return go_one_step(root);
          } else {
            return $(".animation").prop("disabled", false);
          }
        });
      });
      action_croco = find_action_pointer(root);
      if (action_croco.length > 0) {
        return step1.resolve(action_croco);
      } else {
        return $(".animation").prop("disabled", false);
      }
    };
  });

}).call(this);
